AllCops:
  DisplayCopNames: true
  Exclude:
    - 'lib/capistrano/**/*'
    - 'vendor/**/*'
    - 'unicorn.conf.rb'

Metrics/LineLength:
  Max: 120
Metrics/ParameterLists:
  Max: 6

Documentation:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/Not:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/TrailingComma:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/TrailingBlankLines:
  Enabled: false
Style/EmptyLinesAroundClassBody:
  Enabled: false
Style/EmptyLinesAroundModuleBody:
  Enabled: false
Style/FormatString:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
